[package]
name = "async-download"
version = "0.1.0"
authors = ["shantanu28sharma <shantanu28sharma@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = {version="1", features=["full"]}
reqwest = "*"
